# PHP
phpfpm:
  build: ./phpfpm
  restart: always
  volumes:
    - ./public:/var/www/html
  links:
    - mongodb:mongodb

# NGINX
nginx:
  restart: always
  image: nginx:1.10
  ports:
    - "8000:80"
    - "9000:9000"
  links:
    - phpfpm:phpfpm
  volumes:
    - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    - ./public:/var/www/html
    - ./log/nginx:/var/log/nginx

# DB Mongo
mongodb:
  image: mongo:3.2
  ports:
    - "27018:27017"
  volumes:
    - ./mongo/data:/data/db
    - ./log/mongo:/var/log/mongodb
  restart: always
  environment:
      MONGO_LOG_DIR: /var/log/mongodb